In [19]:
import numpy as np

## arange followed by Reshape ##

In [20]:
a = np.arange(15).reshape(3,5)

## Shape ##

In [21]:
a.shape

(3, 5)

## Min ##

In [22]:
a.min()

0

In [23]:
np.min(a)

0

## Max ##

In [24]:
np.max(a)

14

In [25]:
a.max()

14

## Argmin ##

In [26]:
np.argmin(a)

0

In [27]:
np.argmin(a,axis=1)

array([0, 0, 0])

In [28]:
a.argmin()

0

## Argmax ##

In [29]:
np.argmax(a)

14

In [30]:
a.argmax()

14

## Mean ##

In [31]:
a.mean()

7.0

In [32]:
np.mean(a)

7.0

In [33]:
np.mean(a,axis=1)

array([  2.,   7.,  12.])

In [34]:
np.mean(a,axis=0)

array([ 5.,  6.,  7.,  8.,  9.])

## * for Matrix(ElementWise) ##

In [35]:
b = np.arange(15).reshape(3,5)

In [36]:
a*b

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [37]:
c = np.arange(15).reshape(5,3)

## Dot product ##

In [38]:
c.dot(b)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118],
       [115, 136, 157, 178, 199],
       [160, 190, 220, 250, 280],
       [205, 244, 283, 322, 361]])

In [39]:
np.dot(b,c)

array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510]])

## Sum ##

In [40]:
b.sum()

105

## Ravel ##

In [41]:
ravel = a.ravel()

In [42]:
ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Eye ##

In [43]:
u = np.eye(2)

## Identity ##

In [44]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [45]:
y = np.array([[1],[3]])

## Linealg.solve ##

In [46]:
np.linalg.solve(u,y)

array([[ 1.],
       [ 3.]])

## Flatten ##

In [47]:
flatten = u.flatten()

In [48]:
flatten

array([ 1.,  0.,  0.,  1.])

## Diagnol

In [49]:
diagnol = np.diag(a)

In [50]:
diagnol

array([ 0,  6, 12])

## Tril

In [51]:
np.tril(a)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  0,  0,  0],
       [10, 11, 12,  0,  0]])

## Triu

In [52]:
np.triu(a)

array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14]])

# Part B

In [53]:
matrix_a = [[1,2,3],[4,5,6],[7,8,9]]
matrix_b = [[10,11,12],[13,14,15],[16,17,18]]

## Min

In [54]:
def minimum(matrix_a):
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            minimum = matrix_a[0][0]
            if matrix_a[i][j] < minimum :
                minimum = matrix_a[i][j]
    return minimum
minimum(matrix_b)
            

10

# Max

In [55]:
def maximum(matrix_a):
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            maximum = matrix_a[0][0]
            if matrix_a[i][j] > maximum :
                maximum = matrix_a[i][j]
    return maximum
maximum(matrix_b)
            

18

# Mean

In [56]:
def mean(matrix_a):
    sume = 0
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            
            sume = sume + matrix_a[i][j]
    mean = sume/(len(matrix_a)*len(matrix_a[0]))
    return mean
mean(matrix_b)


14.0

# Argmin

In [57]:
def argminimum(matrix_a):
    arg = 0
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            minimum = matrix_a[0][0]
            if matrix_a[i][j] < minimum :
                minimum = matrix_a[i][j]
                arg += 1 
    return arg
argminimum(matrix_b)

0

# Argmax

In [58]:
def argmaximum(matrix_a):
    arg = 0
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            maximum = matrix_a[0][0]
            if matrix_a[i][j] > maximum :
                maximum = matrix_a[i][j]
                arg += 1
    return arg
argmaximum(matrix_b)
#np.argmax(matrix_b)

8

# flatten

In [60]:
def flatten(matrix_a):
    flatten_new = []
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            flatten_new.append(matrix_a[i][j])
    return flatten_new
flatten(matrix_b)

[10, 11, 12, 13, 14, 15, 16, 17, 18]

# ravel

In [62]:
def ravel(matrix_a):
    ravel_new = []
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            ravel_new.append(matrix_a[i][j])
    return ravel_new
ravel(matrix_b)

[10, 11, 12, 13, 14, 15, 16, 17, 18]

# dot product

In [79]:
def product(matrix_a, matrix_b):
    product_matrix = []
    for i in range(len(matrix_a)):
        w = []
        for j in range(len(matrix_b[0])):
            sume = 0
            for k in range(len(matrix_a[0])):
                sume = sume + (matrix_a[i][k] * matrix_b[k][j])
            w.append(sume)
        product_matrix.append(w)
    return product_matrix

product(matrix_a, matrix_b)

[[84, 90, 96], [201, 216, 231], [318, 342, 366]]

In [76]:
np.dot(matrix_a, matrix_b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

# * for matrix(Elementary Product)

In [67]:
def Elementaryproduct(matrix_a, matrix_b):
    product_matrix = []
    for i in list(range(len(matrix_a))):
        w = []
        for j in list(range(len(matrix_a[0]))):
                w.append(matrix_a[i][j] * matrix_b[i][j]) 
        product_matrix.append(w)     
    return(product_matrix)

Elementaryproduct(matrix_a, matrix_b)

[[10, 22, 36], [52, 70, 90], [112, 136, 162]]

# arrange followed by reshape

In [81]:
def reshape(n):
    return(list(range(n)))

reshape(5)

[0, 1, 2, 3, 4]

# Identity/ Eye

In [200]:
def identity(size):
    identity_matrix = []
    
    for i in range(size):
        w = []
        for j in range(size):
            if i == j:
                w.append(1)
            else :
                w.append(0)
        identity_matrix.append(w)
    return identity_matrix
identity(3)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

# Sum

In [148]:
def Sume(matrix_a):
    sume = 0
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            
            sume = sume + matrix_a[i][j]
    return sume
Sume(matrix_b)

126

# Diag

In [164]:
def diag(matrix_a):
    diagnol_matrix = []
    for i in range(len(matrix_a)):
        for j in range(len(matrix_a[0])):
            if i == j :
                diagnol_matrix.append(matrix_a[i][j])
    return diagnol_matrix
diag(matrix_b)

[10, 14, 18]

In [165]:
np.diag(matrix_b)

array([10, 14, 18])

# Tril

In [159]:
def tril(matrix_a):
    tril_matrix = []
    for i in range(len(matrix_a)):
        w=[]
        for j in range(len(matrix_a[0])):
            if i < j :
                w.append(0)
            else :
                w.append(matrix_a[i][j])
        tril_matrix.append(w)
    return tril_matrix
tril(matrix_b)

[[10, 0, 0], [13, 14, 0], [16, 17, 18]]

In [166]:
np.tril(matrix_b)

array([[10,  0,  0],
       [13, 14,  0],
       [16, 17, 18]])

# Triu

In [162]:
def triu(matrix_a):
    triu_matrix = []
    for i in range(len(matrix_a)):
        w=[]
        for j in range(len(matrix_a[0])):
            if i > j :
                w.append(0)
            else :
                w.append(matrix_a[i][j])
        triu_matrix.append(w)
    return triu_matrix
triu(matrix_b)

[[10, 11, 12], [0, 14, 15], [0, 0, 18]]

In [167]:
np.tril(matrix_b)

array([[10,  0,  0],
       [13, 14,  0],
       [16, 17, 18]])